# Generated by Django 3.1.7 on 2021-07-02 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_side', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='book_id',
            new_name='id',
        ),
    ]
