# Generated by Django 3.1.7 on 2021-06-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_side', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_id',
            field=models.CharField(default=2, max_length=30, null=True),
        ),
    ]
