# Generated by Django 3.1.7 on 2021-06-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_side', '0002_issue_issue_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='id',
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
