# Generated by Django 3.1.7 on 2021-04-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_side', '0002_auto_20210406_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.ManyToManyField(to='management_side.Tag'),
        ),
    ]
