# Generated by Django 3.1.7 on 2021-04-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_side', '0003_book_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='category',
            new_name='condition',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
    ]
