# Generated by Django 3.1.7 on 2021-05-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_side', '0008_auto_20210410_2342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='member',
            new_name='customer',
        ),
    ]
