# Generated by Django 3.1.7 on 2021-05-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_side', '0013_auto_20210531_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
